version: '3.9'

services:
  database:
    container_name: propetly-db
    image: postgres:15.7-alpine
    restart: always
    command: postgres -c 'max_connections=1000'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
