# Generated by Django 5.1.1 on 2024-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("bik", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_account",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "correction_account",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "director_last_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_middle_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "director_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
